# Conjunto de dados utilizados
## Pesquisa Nacional por Amostra de Domicílios Contínua Trimestral.

- Pessoas de 14 anos ou mais de idade, total, na força de trabalho, ocupadas, desocupadas, fora da força de trabalho, em situação de informalidade e respectivas taxas e níveis, por sexo.
- **Taxa de desocupação**, na semana de referência, das pessoas de 14 anos ou mais de idade.
- Pesquisa realizada desde o **1º Trimestre de 2012 até 4º Trimestre de 2025**.
- Sexo: Homens e Mulheres.
- Pesquisa realizada apenas no estado de Pernambuco.

-----
## Dicionário

### Significado das Colunas

- **periodo**: Representa a referência temporal dos dados.
    - As datas (ex: 2012-01-01, 2012-04-01) indicam o início de cada trimestre.
    - `2012-01-01`: 1º Trimestre de 2012.
    - `2012-04-01`: 2º Trimestre de 2012, e assim por diante.

- **total**: É o índice geral para toda a população analisada naquele período (provavelmente a taxa de desocupação ou desemprego).

- **homens**: O índice específico para a população masculina.

- **mulheres**: O índice específico para a população feminina.

In [4]:
import pandas as pd

url = "https://docs.google.com/spreadsheets/d/1BRIthYFiT3i39WGEk3AQd24BH8rT4EokJ4WsEiMp1jE/export?format=csv"
data = pd.read_csv(url)
data

       periodo  total  homens  mulheres
0   2012-01-01    9.6     7.1      13.1
1   2012-04-01    8.3     6.4      11.0
2   2012-07-01    9.4     7.6      11.8
3   2012-10-01    9.2     7.9      11.1
4   2013-01-01   10.7     8.2      14.2
5   2013-04-01    9.7     8.3      11.7
6   2013-07-01    8.5     6.6      11.2
7   2013-10-01    7.4     6.1       9.3
8   2014-01-01    8.8     7.4      10.9
9   2014-04-01    8.0     7.2       9.2
10  2014-07-01    8.5     7.4       9.9
11  2014-10-01    7.7     6.7       9.1
12  2015-01-01    8.2     6.8      10.2
13  2015-04-01    9.2     8.3      10.4
14  2015-07-01   11.3    10.1      12.9
15  2015-10-01   11.1    10.3      12.3
16  2016-01-01   13.4    12.5      14.8
17  2016-04-01   14.2    13.0      15.9
18  2016-07-01   15.5    14.0      17.5
19  2016-10-01   15.9    14.3      18.2
20  2017-01-01   17.3    15.5      19.9
21  2017-04-01   19.0    17.4      21.2
22  2017-07-01   18.1    17.1      19.3
23  2017-10-01   17.0    15.8      18.6
24  2018-01-01   17.9    17.4      18.6
25  2018-04-01   17.1    16.7      17.7
26  2018-07-01   17.0    15.9      18.5
27  2018-10-01   15.6    13.8      18.0
28  2019-01-01   16.3    14.2      19.1
29  2019-04-01   16.1    14.5      18.3
30  2019-07-01   16.0    13.3      19.6
31  2019-10-01   14.2    12.3      16.6
32  2020-01-01   14.8    13.4      16.7
33  2020-04-01    0.0     0.0       0.0
34  2020-07-01    0.0     0.0       0.0
35  2020-10-01    0.0     0.0       0.0
36  2021-01-01    0.0     0.0       0.0
37  2021-04-01    0.0     0.0       0.0
38  2021-07-01    0.0     0.0       0.0
39  2021-10-01    0.0     0.0       0.0
40  2022-01-01    0.0     0.0       0.0
41  2022-04-01   13.6    11.0      17.0
42  2022-07-01   14.0    11.0      17.8
43  2022-10-01   12.3    10.0      15.5
44  2023-01-01   14.1    11.8      17.2
45  2023-04-01   14.2    12.5      16.4
46  2023-07-01   13.3    11.5      15.7
47  2023-10-01   12.0    10.2      14.4
48  2024-01-01   12.4    10.3      15.2
49  2024-04-01   11.6    10.0      13.6
50  2024-07-01   10.6     8.9      12.9
51  2024-10-01   10.3     8.1      13.0
52  2025-01-01   11.6     9.7      14.0
53  2025-04-01   10.4     9.3      11.8
54  2025-07-01   10.0     8.0      12.8
55  2025-10-01    8.8     8.2       9.7

In [3]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 56 entries, 0 to 55
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   periodo   56 non-null     str
 1   total     56 non-null     float64
 2   homens    56 non-null     float64
 3   mulheres  56 non-null     float64
dtypes: float64(3), str(1)
memory usage: 1.9 KB

## Médias bienal

In [38]:
data = data[data['total'] != 0]

In [67]:
anos_remover = [2020, 2021, 2022, 2026]

In [68]:
data_filtrada = data[~data['periodo'].dt.year.isin(anos_remover)]

In [69]:
data['periodo'] = pd.to_datetime(data['periodo'])

In [70]:
data_filtrada.info()

<class 'pandas.DataFrame'>
Index: 44 entries, 0 to 55
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   periodo   44 non-null     datetime64[us]
 1   total     44 non-null     float64
 2   homens    44 non-null     float64
 3   mulheres  44 non-null     float64
dtypes: datetime64[us](1), float64(3)
memory usage: 1.7 KB

In [71]:
data_bienal = data_filtrada.groupby(pd.Grouper(key='periodo', freq='2YE')).mean()

In [72]:
data_bienal = data_bienal.dropna(how='all')
data_bienal = data_bienal[~data_bienal.index.year.isin(anos_remover)]

In [73]:
data_bienal

              total   homens  mulheres
periodo
2012-12-31   9.1250   7.2500   11.7500
2014-12-31   8.6625   7.2375   10.6875
2016-12-31  12.3500  11.1625   14.0250
2018-12-31  17.3750  16.2000   18.9750
2024-12-31  12.3125  10.4125   14.8000

###  Comparação Homens x Mulheres, o sexo influencia a desocupação?

In [78]:
data_bienal['homens'].sum()

np.float64(52.262499999999996)

In [77]:
data_bienal['mulheres'].sum()

np.float64(70.2375)